"use client";

import { motion } from "motion/react";
import { CheckCircle2 } from "lucide-react";

import { Stagger, StaggerItem } from "@/components/shared/motion";
import { AutosaveIndicator } from "@/features/ifu-wizard/components/AutosaveIndicator";
import type { IfuDocument } from "@/features/ifu-wizard/types";
import { EASE_OUT_EXPO } from "@/lib/motion";

import type { StructuredValues } from "../schema";
import type { SectionDef } from "../types";
import { ComplianceTip } from "./ComplianceTip";
import { ManufacturerLicencePreview } from "./ManufacturerLicencePreview";
import { RichTextField } from "./RichTextField";
import { SectionFooterActions } from "./SectionFooterActions";
import { StructuredFields, type StructuredErrors } from "./StructuredFields";

interface SectionEditorPresentationProps {
  definition: SectionDef;
  document: IfuDocument;
  values: Record<string, string>;
  structured: StructuredValues;
  isComplete: boolean;
  focusField?: string;
  saveState: "saving" | "saved";
  fieldErrors: Record<string, string>;
  structuredErrors: StructuredErrors;
  isBursting: boolean;
  previousHref: string | null;
  exitHref: string;
  completeLabel: string;
  onFieldChange: (fieldKey: string, value: string) => void;
  onStructuredChange: (patch: Partial<StructuredValues>) => void;
  onComplete: () => void;
}

export const SectionEditorPresentation = ({
  definition,
  document,
  values,
  structured,
  isComplete,
  focusField,
  saveState,
  fieldErrors,
  structuredErrors,
  isBursting,
  previousHref,
  exitHref,
  completeLabel,
  onFieldChange,
  onStructuredChange,
  onComplete,
}: SectionEditorPresentationProps) => (
  <motion.section
    key={definition.key}
    aria-labelledby="section-title"
    initial={{ opacity: 0, y: 14 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.45, ease: EASE_OUT_EXPO }}
    className="flex flex-col gap-6 rounded-2xl border bg-card p-5 shadow-sm sm:p-7"
  >
    <header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
      <div>
        <div className="flex flex-wrap items-center gap-2">
          <h2 id="section-title" className="text-xl font-semibold tracking-tight">
            {definition.title}
          </h2>
          {isComplete && (
            <motion.span
              initial={{ scale: 0.6, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="inline-flex items-center gap-1 rounded-full bg-success-soft px-2 py-0.5 text-xs font-medium text-success-soft-foreground ring-1 ring-inset ring-success/30"
            >
              <CheckCircle2 aria-hidden className="size-3.5" /> Complete
            </motion.span>
          )}
        </div>
        <p className="mt-1 text-sm text-muted-foreground">{definition.description}</p>
      </div>
      {!definition.autoGenerated && <AutosaveIndicator state={saveState} label="Saved" />}
    </header>

    {definition.autoGenerated ? (
      <ManufacturerLicencePreview document={document} />
    ) : (
      <Stagger trigger="mount" stagger={0.07} className="flex flex-col gap-5">
        {definition.fields.map((field, index) => (
          <StaggerItem key={field.key}>
            <RichTextField
              id={`field-${field.key}`}
              label={field.label}
              placeholder={field.placeholder}
              value={values[field.key] ?? ""}
              error={fieldErrors[field.key]}
              autoFocus={focusField ? focusField === field.key : false}
              onChange={(value) => onFieldChange(field.key, value)}
            />
            {index === definition.fields.length - 1 && definition.structured && (
              <div className="mt-5">
                <StructuredFields
                  kinds={definition.structured}
                  values={structured}
                  errors={structuredErrors}
                  onChange={onStructuredChange}
                />
              </div>
            )}
          </StaggerItem>
        ))}
      </Stagger>
    )}

    <ComplianceTip tip={definition.tip} />

    <SectionFooterActions
      previousHref={previousHref}
      exitHref={exitHref}
      completeLabel={completeLabel}
      isBursting={isBursting}
      onComplete={onComplete}
    />
  </motion.section>
);
