import type { IfuDocumentSummary } from "@/features/ifu-wizard/types";

export const MOCK_DOCUMENTS: IfuDocumentSummary[] = [
  { id: "demo", deviceName: "OrthoFix Cortical Bone Screw", modelNumber: "OF-CS-35", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "IMPLANT", riskClass: "C", status: "DRAFT", version: "v1.0", lastStep: "SECTIONS", updatedAt: "2026-10-04T09:12:00+05:30" },
  { id: "doc-02", deviceName: "GlucoSure Blood Glucose Test Strips", modelNumber: "GS-50", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "IVD", riskClass: "B", status: "READY", version: "v1.0", lastStep: "REVIEW", updatedAt: "2026-10-03T16:40:00+05:30" },
  { id: "doc-03", deviceName: "SafeFlow IV Cannula", modelNumber: "SF-20G", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "SINGLE_USE", riskClass: "B", status: "COMPLETED", version: "v1.1", lastStep: "REVIEW", updatedAt: "2026-10-01T11:05:00+05:30" },
  { id: "doc-04", deviceName: "SteriCut Surgical Scissors", modelNumber: "SC-14", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "REUSABLE", riskClass: "A", status: "COMPLETED", version: "v2.0", lastStep: "REVIEW", updatedAt: "2026-09-28T14:22:00+05:30" },
  { id: "doc-05", deviceName: "CardioTrack ECG Analysis App", modelNumber: "CT-APP-2", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "SAMD", riskClass: "B", status: "DRAFT", version: "v1.0", lastStep: "CATEGORY_RISK", updatedAt: "2026-09-27T10:00:00+05:30" },
  { id: "doc-06", deviceName: "VeriStent Coronary Stent System", modelNumber: "VS-300", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "IMPLANT", riskClass: "D", status: "DRAFT", version: "v1.0", lastStep: "BASIC_INFO", updatedAt: "2026-09-25T18:45:00+05:30" },
  { id: "doc-07", deviceName: "RapidCheck Dengue NS1 Antigen Kit", modelNumber: "RC-NS1-25", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "IVD", riskClass: "C", status: "COMPLETED", version: "v1.0", lastStep: "REVIEW", updatedAt: "2026-09-20T09:30:00+05:30" },
  { id: "doc-08", deviceName: "ClearView Digital Thermometer", modelNumber: "CV-T10", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "OTHER", riskClass: "B", status: "READY", version: "v1.0", lastStep: "REVIEW", updatedAt: "2026-09-18T12:15:00+05:30" },
  { id: "doc-09", deviceName: "SutureLine Absorbable Suture", modelNumber: "SL-3-0", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "SINGLE_USE", riskClass: "C", status: "COMPLETED", version: "v1.2", lastStep: "REVIEW", updatedAt: "2026-09-10T15:50:00+05:30" },
  { id: "doc-10", deviceName: "FlexiScope Reusable Laryngoscope", modelNumber: "FS-MAC3", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "REUSABLE", riskClass: "B", status: "DRAFT", version: "v1.0", lastStep: "SECTIONS", updatedAt: "2026-09-05T08:20:00+05:30" },
  { id: "doc-11", deviceName: "OxiPulse Fingertip Oximeter", modelNumber: "OP-200", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "OTHER", riskClass: "B", status: "COMPLETED", version: "v1.0", lastStep: "REVIEW", updatedAt: "2026-08-29T17:35:00+05:30" },
  { id: "doc-12", deviceName: "DermaPatch Hydrocolloid Dressing", modelNumber: "DP-10x10", manufacturerName: "Sanjeevani MedTech Pvt. Ltd.", category: "SINGLE_USE", riskClass: "A", status: "COMPLETED", version: "v1.0", lastStep: "REVIEW", updatedAt: "2026-08-14T13:10:00+05:30" },
];
