import type { SectionKey } from "@/features/ifu-wizard/types";

export type SectionStructuredKind = "storage" | "sterilisation" | "shelfLife";

export interface SectionFieldDef {
  key: string;
  label: string;
  placeholder: string;
  minLength: number;
}

export interface SectionDef {
  key: SectionKey;
  title: string;
  description: string;
  tip: string;
  /** Plain-language reason shown in the Step 2 "we'll include" panel. */
  includeReason: string;
  fields: SectionFieldDef[];
  structured?: SectionStructuredKind[];
  /** Auto-generated sections are previewed read-only rather than edited. */
  autoGenerated?: boolean;
}

export type SectionProgressState = "complete" | "current" | "not_started";
